version: '3'

services:
  keenetic_prometheus_exporter:
    ports:
      - "60006:6789"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/7F5DCC5C7797EDE5/Releases/docker/storage:/storage
    environment:
      - RABBIT_AMPQ_URL=amqp://guest:guest@my_rabbit:5672
      - CONFIG_PATH=/storage/metrics.json
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network