configuration: '0.2'
discord_bot: '0.10'
docker_bot: '0.1'
iptv_filter: '0.3'
jira_tracker: '0.1'
keenetic_prometheus_exporter: '0.3'
outlook: '0.2'
soundcloud: '0.4'
todoist: '0.1'
web_host: '0.7'
worklog_kpi: '0.2'
yandex: '0.1'
