version: '3'

volumes:
  db-data:

services:
  postgres:
    image: postgres:11.3
    ports:
      - "5432:5432"
    container_name: pgdb
    hostname: postgres
    networks:
      mnemo-network:
        aliases:
          - pgdb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prod
  
networks:
  mnemo-network:
    driver: "bridge