version: '3'

services:
  discord:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: discord
    working_dir: /app
    command: python ./executers/discord_bot_main.py
    volumes:
      - ../../:/app
    environment:
      - RABBIT_HOST=192.168.0.1
      - RABBIT_PORT=5672
      - DISCORD_TOKEN=token
    restart: always
    network_mode: "bridge"
