version: '3'

services:
  discord:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: discord
    working_dir: /app
    hostname: discord_bot
    command: python ./executers/discord_bot_main.py
    volumes:
      - ../../:/app
    environment:
      - RABBIT_HOST=my_rabbit
      - RABBIT_PORT=5672
      - DISCORD_TOKEN=Token
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network
