version: '3'

services:
  soundcloud:
    volumes:
      - /mnt/7F5DCC5C7797EDE5/Для разбора/Музыка:/downloads
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - RABBIT_AMPQ_URL=amqp://guest:guest@my_rabbit:5672
      - DOWNLOAD_DIRECTORY_PATH=/downloads
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network