version: '3'

services:
  outlook:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: outlook
    working_dir: /app
    hostname: outlook
    command: python ./executers/outlook_main.py
    volumes:
      - ../../:/app
    environment:
      - RABBIT_HOST=my_rabbit
      - RABBIT_PORT=5672
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network

