version: '3'

services:
  worklog:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: worklog
    working_dir: /app
    hostname: worklog_bot
    command: python /app/executers/wokrlog_main.py
    volumes:
      - ../../:/app
    environment:
      - RABBIT_HOST=my_rabbit
      - RABBIT_PORT=5672
      - PYTHONUNBUFFERED=1;
      - TODOIST_API_TOKEN=TOKEN
    restart: unless-stopped
    network_mode: bridge

