version: '3'

services:
  web_host:
    ports:
      - "60009:6789"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/7F5DCC5C7797EDE5/Releases/docker/storage:/storage
    environment:
      - RABBIT_AMPQ_URL=amqp://guest:guest@my_rabbit:5672
      - PYTHONUNBUFFERED=1
      - STATIC_PATH=/app/pages
      - IPTV_PLAYLIST_PATH=/storage/custom.m3u
      - IPTV_EPG_PATH=/storage/epg.xml
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network

