version: '3'

services:
  telegram_bot:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./tmp:/tmp
    environment:
      - RABBIT_AMPQ_URL=amqp://guest:guest@my_rabbit:5672
      - PYTHONUNBUFFERED=1
      - DOWNLOAD_DIRECTORY_PATH=/tmp
    restart: unless-stopped

networks:
  default:
    external:
      name: internal_network
